# .travis.yml
sudo: false
language: php

php:
  - 7.2
  - 7.3

env:
  - TYPO3_VERSION=^9 TESTING_VERSION=^4
  - TYPO3_VERSION=^10 TESTING_VERSION=^5

addons:
  apt:
    packages:
      - parallel

install:
  - composer require typo3/minimal:${TYPO3_VERSION} typo3/testing-framework=${TESTING_VERSION}
  - git checkout composer.json
  - export TYPO3_PATH_WEB="$PWD/.build/web"

script:
  - >
    echo;
    echo "PHP lint";
    if find . -name \*.php ! -path "./.Build/*" ! -path "./vendor/*" ! -path "./public/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; else echo "OK"; fi;
  - >
    echo;
    echo "Functional Testing";
    .Build/bin/phpunit --configuration Tests/Functional/phpunit.xml;
jobs:
  include:
    - stage: quality
      php: 7.2
      script: composer cgl

cache:
  directories:
    - $HOME/.composer/cache